name: vincibean
version: '0.1.0.0'
category: Web
author: Andre Bessi
maintainer: andrebessi00@gmail.com
copyright: 2019 Andre Bessi
license: GPL-3.0
homepage: https://vincibean.github.io/
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- hakyll
executables:
  site:
    main: site.hs
    source-dirs: site
    ghc-options: -threaded
