version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            # find a cache for the same stack.yaml
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            # when missing reuse from the same branch
            - stack-{{ .Branch }}-
            # when missing reuse the latest cache
            - stack-
      - run:
          name: Update and Install SSH
          command: apt-get update && apt-get install --yes ssh
      - add_ssh_keys:
          fingerprints:
            - "dc:aa:9d:e6:6d:d8:96:2e:3b:e2:4c:55:8a:bc:1e:fe"
      - run:
          name: Resolve and Update Dependencies
          command: |
            stack setup
            stack build --dependencies-only
      - save_cache:
          name: Cache Dependencies
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build Site App
          command: stack build --pedantic
      - run:
          name: Generate Static Site
          command: stack exec vincibean build
      - run:
          name: Publish GitHub Pages
          working_directory: './_site'
          command: |
            # Establishing authenticity of host 'github.com'
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            # initalize repo
            git init
            git config user.name  'CircleCI'
            git config user.email 'job@circleci.com'
            # add generated files
            git add .
            git commit -m "publish $CIRCLE_SHA1 [ci skip]"
            # push to pages branch
            git remote add origin "$CIRCLE_REPOSITORY_URL"
            git push --force origin master
